name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: builder
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.4.1
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: Bankiut
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'zulu'

      - name: Verify SQL files exist
        run: |
          if [ ! -f "$GITHUB_WORKSPACE/script/bankiut.sql" ]; then
            echo "Error: bankiut.sql not found!"
            exit 1
          fi
          if [ ! -f "$GITHUB_WORKSPACE/script/bankiuttest.sql" ]; then
            echo "Error: bankiuttest.sql not found!"
            exit 1
          fi

      - name: Wait for MariaDB to be ready
        run: |
          until docker exec $(docker ps -q --filter "ancestor=mariadb:10.4.1") mysqladmin --user=root --password=root ping --silent; do
            echo "Waiting for MariaDB to be ready..."
            sleep 5
          done

      - name: Create databases
        run: |
          docker exec $(docker ps -q --filter "ancestor=mariadb:10.4.1") mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS Bankiut;"
          docker exec $(docker ps -q --filter "ancestor=mariadb:10.4.1") mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS Bankiut_test;"

      - name: Copy and Import SQL files
        run: |
          echo "Copying and importing bankiut.sql..."
          docker cp "$GITHUB_WORKSPACE/script/bankiut.sql" $(docker ps -q --filter "ancestor=mariadb:10.4.1"):/tmp/bankiut.sql || { echo "Error: Failed to copy bankiut.sql"; exit 1; }
          docker exec $(docker ps -q --filter "ancestor=mariadb:10.4.1") mysql -u root -proot Bankiut < /tmp/bankiut.sql || { echo "Error: Failed to import bankiut.sql"; exit 1; }

          echo "Copying and importing bankiuttest.sql..."
          docker cp "$GITHUB_WORKSPACE/script/bankiuttest.sql" $(docker ps -q --filter "ancestor=mariadb:10.4.1"):/tmp/bankiuttest.sql || { echo "Error: Failed to copy bankiuttest.sql"; exit 1; }
          docker exec $(docker ps -q --filter "ancestor=mariadb:10.4.1") mysql -u root -proot Bankiut_test < /tmp/bankiuttest.sql || { echo "Error: Failed to import bankiuttest.sql"; exit 1; }

      - name: Run SonarQube Analysis
        working-directory: ./_00_ASBank2023
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Bos-Allan_BUT3_GR4
